### ISSUE TITLE
Update for Julia 1.x?

### ISSUE THREAD

**Issue by aaowens** [floswald/Tasmanian.jl#4]
Thanks for the package. It works fine on later versions of Julia, so maybe you should update the Travis CI to include 1.x. 

I used this package here https://github.com/aaowens/global_solution_methods_Rochester/blob/master/SparseGrids.ipynb to do value function iteration on adaptive sparse grids.

One point: I noticed a substantial speedup(about 10x) when I compiled the Tasmanian library myself, instead of using your bundled library. There is also a new version of Tasmanian available, but it has some API changes so it can't be substituted instantly.

**Comment by floswald** [comment]
hey, that's cool! 

* 10x is quite something! yes, it was a while ago that i built those libraries. still surprising that there is such a difference in speed. I thought the idea of the binary builder was to get rid of local specialized builds? 
* nice notebook!
* will update the travis (or you send PR :wink:)
